classDiagram
    class MaterialBiblioteca {
        -codigo: str
        -titulo: str
        -prestado: bool
        -fecha_devolucion: ~datetime~
        +calcular_fecha_devolucion() datetime
        +prestar() bool
    }

    class Libro {
        +calcular_fecha_devolucion() datetime
    }

    class Revista {
        +calcular_fecha_devolucion() datetime
    }

    class DVD {
        +calcular_fecha_devolucion() datetime
    }

    MaterialBiblioteca <|-- Libro
    MaterialBiblioteca <|-- Revista
    MaterialBiblioteca <|-- DVD

